#+SETUPFILE: css/level-0.orgcss

#+HTML: <script src="js/bootstrap.min.js"></script>
#+HTML: <script src="js/jquery-1.9.1.min.js"></script>



* Evan Misshula 
[[file:index.org][Evan]]
[[file:Academic.org][Academic]]
[[file:contact.org][contact]]


** Academic  
   I am a fifth year PhD student in Criminal Justice at the CUNY Graduate
   Center.  I work as a data scientist at the John Jay Research and
   Evaluation Center where I evaluate anti-violence programs. I serve
   as a CUNY John Jay Presidential Fellow where I work on the
   Misdemeanor Project. At John Jay I am a member of the Prison 2
   Public Health group and the Social Network Research Group.  At the
   CUNY GC, I am a member of the Pattern Recognition Lab.
** Advocacy and charitable work 
   I mentor for the College Initiative, a project which helps people
   returning from prison access higher education.  I serve on the
   Men's Advisory Board for the Prison Visiting Project of Corrections
   Association of New York and the research advisory board of the New
   York Public Library. I am a member of the NYC Open Data, NYC
   Python, Emacsnyc and the NYC Code for America Brigade.
** Resume
   Here is a link to my resume.
** Research Interests
   I am interested in prisoner reentry and economic mobility, broadly
   defined.
** Publication
   Here is a link to my google scholar page
** Social media
   - Email: EMisshula(at)jjay(dot)cuny(dot)edu
   - Twitter: @EMisshula
   - Blog: https://mofj.commons.gc.cuny.edu/
   - Github: https://github.com/EvanMisshula

